// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    FirebaseAuth.instance.idTokenChanges();
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHNAqTll-2vhwIE09pzPP9ySLgOVVhoao',
    appId: '1:853163869020:web:bf4a5a8cb3f42f152f3799',
    messagingSenderId: '853163869020',
    projectId: 'instagram-54e25',
    authDomain: 'instagram-54e25.firebaseapp.com',
    storageBucket: 'instagram-54e25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEU1NgVDst4SXONxB-uAHSi-WKstTiBkA',
    appId: '1:853163869020:android:af7e2ebe5a0670442f3799',
    messagingSenderId: '853163869020',
    projectId: 'instagram-54e25',
    storageBucket: 'instagram-54e25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATkP6iya31YbzpLXLACMfhPvCZgoPj16I',
    appId: '1:853163869020:ios:10f17ff53e6f77d82f3799',
    messagingSenderId: '853163869020',
    projectId: 'instagram-54e25',
    storageBucket: 'instagram-54e25.appspot.com',
    iosClientId:
        '853163869020-pkm039qap5nufnladq106ruho15vpamu.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATkP6iya31YbzpLXLACMfhPvCZgoPj16I',
    appId: '1:853163869020:ios:6e9ea803832ad11b2f3799',
    messagingSenderId: '853163869020',
    projectId: 'instagram-54e25',
    storageBucket: 'instagram-54e25.appspot.com',
    iosClientId:
        '853163869020-mgjee9qp1j0rhit9d9gq4an5q2hn84j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
